services:
  app:
    build:
      context: .
      target: prod
    container_name: acquisitions-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
